title: Xun Li
description: My Personal Blog
author: Xun Li
logo: http://lixun910.github.io/static/img/avatar.png
github: https://github.com/lixun910
about: Dev for Map
disqus_shortname: lixun910
google_analytics: UA-74286861-1
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Github
      url: https://github.com/lixun910
      icon: fa-github
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed
    - text: Resume
      url: '/resume/'
      icon: fa-graduation-cap

social:
    - icon: fa-facebook
      link: 'https://www.facebook.com/lixun910'
    - icon: fa-skype
      link: 'https://www.skype.com/lixun910'
    - icon: fa-twitter
      link: 'https://twitter.com/lixun910'
    - icon: fa-linkedin
      link: 'https://www.linkedin.com/in/xun-li-794a5b18'
    #- icon: fa-stack-exchange
    #  link: '#'

share:
  twitter_username: lixun910
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "http://lixun910.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
