title: Xun Li
description: My Personal Blog
author: Xun Li
logo: http://aboutashu.com/hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/lixun910
about: Dev for Map
disqus_shortname: lixun910
google_analytics: UA-74286861-1
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: About
      url: /about/
      icon: fa-comments
    - text: Github
      url: https://github.com/ashutosh2k12
      icon: fa-github
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed
    - text: Resume
      url: '#'
      icon: fa-graduation-cap

social:
    - icon: fa-facebook
      link: '#'
    - icon: fa-skype
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-linkedin
      link: '#'
    #- icon: fa-stack-exchange
    #  link: '#'

share:
  twitter_username: lixun910
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "http://aboutashu.com/hcz-jekyll-blog"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
